server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    path: /error
    include-stacktrace: always
    include-message: always

logging:
  level:
    ROOT: INFO

#https://medium.com/devops-dudes/securing-spring-boot-rest-apis-with-keycloak-1d760b2004e
keycloak:
  auth-url: http://localhost:9080/auth
  client-id: web_app
  client-secret: web_app
  ssl-required: none
  auth-server-url: ${keycloak.auth-url}
  bearer-only: true
  credentials:
    secret: ${keycloak.client-secret}
  realm: entando
  resource: ${keycloak.client-id}
  use-resource-role-mappings: true

app:
  version: 1
  name: entando-hub-catalog
  security:
    auth-server-url: ${keycloak.auth-server-url}
    realm: ${keycloak.realm}
    client-ui: entando-web

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase.enabled: true
  liquibase.change-log: classpath:config/changelog/master.xml

# CORS Configyrations
ALLOWED_ORIGIN:

# Hub UI url for bundle groups
#HUB_GROUP_DETAIL_BASE_URL: