name: Post merge workflow
on:
  push:
    branches:
      - develop
      - release/*
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Pack the application bundle
        id: pack
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: cecchisandrone
        run: |
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          # Needed to build node-sass
          apk add python3
          versionSuffix=SNAPSHOT
          cd application
          bash ../.github/functions/utils.sh setBundleVersion -$versionSuffix
          bash ../.github/functions/utils.sh setComponentVersions -$versionSuffix
          ent --debug bundle pack --org $DOCKER_ORG --stdout --fail-fast
          ent --debug bundle publish
          version=$(bash ../.github/functions/utils.sh getBundleImage)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Publish artifact version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Published bundle image: `${{ steps.pack.outputs.VERSION }}`
  layout-build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Pack the layout bundle
        id: pack
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: cecchisandrone
        run: |
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          versionSuffix=SNAPSHOT
          cd content
          bash ../.github/functions/utils.sh setBundleVersion -$versionSuffix
          ent --debug bundle pack --org $DOCKER_ORG --stdout
          ent --debug bundle publish
          version=$(bash ../.github/functions/utils.sh getBundleImage)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Publish artifact version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Published bundle image: `${{ steps.pack.outputs.VERSION }}`